### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by ericLemanissier** [comment]
why the heck is it trying to run `conan install . -g=cmake --build=outdated --update` when we ask for `conan_cmake_install(PATH_OR_REFERENCE ".." UPDATE BUILD outdated)` ? It's probably the error you got locally?

**Comment by patricia-gallardo** [comment]
> why the heck is it trying to run `conan install . -g=cmake --build=outdated --update` when we ask for `conan_cmake_install(PATH_OR_REFERENCE ".." UPDATE BUILD outdated)` ? It's probably the error you got locally?

Yeah, that was the errors that I was getting when I said I could get the syntax right

**Comment by ericLemanissier** [comment]
ok, PATH_OR_REFERENCE was not in cmake-conan V0.15 !

**Comment by patricia-gallardo** [comment]
With the right conan.cmake this kind of worked
```
    if (UPDATE_CONAN)
        conan_cmake_install(PATH_OR_REFERENCE ${CMAKE_SOURCE_DIR}/conanfile.py UPDATE BUILD outdated)
    else ()
        conan_cmake_install(PATH_OR_REFERENCE ${CMAKE_SOURCE_DIR}/conanfile.py BUILD missing)
    endif ()
```
Except now we're back at the missing Qt6Config.cmake

**Comment by ericLemanissier** [comment]
are these file present in the build folder ?

**Comment by patricia-gallardo** [comment]
> are these file present in the build folder ?
Yes
./cmake-build-release/src/Qt6Config.cmake

**Comment by patricia-gallardo** [comment]
This seems to have done something
list(APPEND CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR}/src/)

**Pull request closed without merging**
